EXPERIMENT:
  NAME: ""
  TAG: "wkd_f,wrn_40_2,shuv1"
  PROJECT: "cifar100_baselines"
  SEED: 10
DISTILLER:
  TYPE: "WKD"
  TEACHER: "wrn_40_2"
  STUDENT: "ShuffleV1"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
WKD:
  INPUT_SIZE: (32, 32)
  LOSS:
    CE_WEIGHT: 1.0
    WKD_LOGIT_WEIGHT: 0.0
    WKD_FEAT_WEIGHT: 0.3
    COSINE_DECAY_EPOCH: 150
  EPS: 0.00001
  HINT_LAYER: -1
  MEAN_COV_RATIO: 3.0
  PROJECTOR: "conv1x1"
  SPATIAL_GRID: 4
LOG:
  WANDB: True
  TENSORBOARD_FREQ: 10
  SAVE_CHECKPOINT_FREQ: 100