EXPERIMENT:
  NAME: ""
  TAG: "wkd_l,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
  SEED: 42
DISTILLER:
  TYPE: "WKD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
  DICT_PATH: "path/to/your/f2pre_dict.pt"
  LOSS_WEIGHT: 5.0
  NAME: "SPARSE"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
WKD:
  INPUT_SIZE: (32, 32)
  LOSS:
    CE_WEIGHT: 1.0
    WKD_LOGIT_WEIGHT: 200.0
    WKD_FEAT_WEIGHT: 0.0
    COSINE_DECAY_EPOCH: 150
    FEAT_WEIGHT: 10000.0
  SINKHORN:
    LAMBDA: 0.05
    ITER: 10
  COST_MATRIX: 'cka'
  COST_MATRIX_PATH: "/kaggle/working/wassterin_dill/wkd_cost_matrix/cifar100/resnet32x4/linear_cka.pth"
  COST_MATRIX_SHARPEN: 1.0
  TEMPERATURE: 8.0
LOG:
  WANDB: True
  TENSORBOARD_FREQ: 10
  SAVE_CHECKPOINT_FREQ: 100
